version: "3"

services:
  v2ray:
    image: teddysun/v2ray
    restart: unless-stopped
    ports:
      - 10001:10001
    volumes:
      - ./v2ray:/etc/v2ray
    depends_on:
      - caddy

  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 127.0.0.1:10002:10001
    volumes:
      - ./www:/usr/src
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./ssl:/data/caddy/certificates
