version: "3.7"

services:
  v2ray:
    image: teddysun/v2ray:5.4.0
    restart: unless-stopped
    ports:
      - "10001:10001"
    volumes:
      - ./v2ray:/etc/v2ray
    depends_on:
      - caddy
    networks:
      - v2ray_net

  caddy:
    image: caddy:2.6.4-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./www:/usr/src
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./ssl:/data/caddy/certificates
    networks:
      - v2ray_net

networks:
  v2ray_net:
    external: true
