version: "3"

services:
  v2ray:
    image: teddysun/v2ray:5.4.0
    restart: unless-stopped
    ports:
      - "10001:10001"
    volumes:
      - ./v2ray:/etc/v2ray
    depends_on:
      - caddy

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "127.0.0.1:10002:10001"
    volumes:
      - ./www:/usr/src
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./ssl:/data/caddy/certificates
